### PR TITLE
Update jest peer dep to support Jest v23

### PR DESCRIPTION
**Pull request by skevy**
## Summary

Updates the Jest peer dep to support Jest v23.

## Test Plan

Tested a ton of tests that use jest-wrap with Jest v23.

### CODE REVIEW

**Comment by skevy** [comment]
Oh shoot! I didn't see that. Thanks folks, will update :)

**Comment by skevy** [comment]
This is what I get for editing through Github :p

PTAL

**Comment by ljharb** [comment]
@skevy please also update travis.yml so that tests are actually ran with jest 23

**Comment by skevy** [comment]
Ok. Time to stop being lazy and actually pull down the code. :) Thanks for being thorough.

**Comment by ljharb** [comment]
I think jest 22 or 23 dropped support for node 4; if any node 4s fail, i'll tweak things to address it.

**Comment by skevy** [comment]
Should be good to go now @ljharb.

**Pull request merged**
